name: Repository Monitor

on: 
  create:
    
jobs:
  repository-created:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - name: "Hello World"
        run: echo "Hello World"
