name: Repository Monitor

on: 
  repository_dispatch:
    types: [created]
    
jobs:
  repository-monitor:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - name: "Hello World"
        run: echo "Repository ${{ github.event.repository.name }} created"
